### ISSUE TITLE
should verify if json resource exists if not use default one

### ISSUE THREAD

**Issue by ghost** [andreabbondanza/DewXamarinLocalization#2]
suggestion for loaddictionary method to avoid null errors

defaultCulture="en-us";

if(resourceNames.Contains(resourceName)==false)
 using (Stream s = assembly.GetManifestResourceStream($"{mainNs}.Localized.{defaultCulture}.json"))
else
 using (Stream s = assembly.GetManifestResourceStream($"{mainNs}.Localized.{culture}.json"))

**Comment by andreabbondanza** [comment]
Hello jose,
Good idea, I think that a good choice for the default culture should be the current culture, something like this:
```csharp
 try
 {
        s = assembly.GetManifestResourceStream($"{mainNs}.Localized.{culture}.json");
        if (s == null)
              s = assembly.GetManifestResourceStream($"{mainNs}.Localized.{CultureInfo.CurrentCulture.Name.ToLower()}.json");
        using (StreamReader sr = new StreamReader(s))
         {
             json = await sr.ReadToEndAsync();
            _localizer.LoadDictionary(Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
         }
}
finally
{
    s?.Dispose();
}
```

**Comment by ghost** [comment]
that would force to have the user's locale,the solution i point would force to set the default culture and then if doesn't exist to load strings from that resource file

**Comment by andreabbondanza** [comment]
We can force tu set a defaultcuture but we can't force to have the defaultcutlure's file. The null problem will be always present.
However we can add a property DefaultCulture to the file, in this way the default culture is set by the developer (and isn't the locale) and use it in the way I've described above. This should be similar to your solution.
What do you think?

**Comment by ghost** [comment]
it could be, we should try

**Comment by andreabbondanza** [comment]
I've done it and it works right. Thanks for your support, I think we can close the issue now.
